name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          # install .codedoc dependencies
          (cd .codedoc && npm install)
          # install codedoc
          npm install @codedoc/cli
          # build repo
          (PATH=$(npm bin):$PATH && codedoc build)
          # copy assets
          cp favicon.ico dist/
          cp favicon-16x16.png dist/
          cp favicon-32x32.png dist/
          cp android-chrome-192x192.png dist/
          cp android-chrome-384x384.png dist/
          cp mstile-150x150.png dist/
          cp README.md dist/
          cp logo-pink.png dist/
          cp logo-dark.png dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist 